# fwe-team <fwe-team.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCMHDOAGG65FSS657OLWFZWFDZUIDOKWCR2T73ZODPZYPPM3NK3YHOLY"
]

[DOCUMENTATION]
ORG_NAME="fwe-team"
ORG_URL="https://fwe-team.github.io"
ORG_LOGO = "https://fwe-team.github.io/img/fwe.png"
ORG_OFFICIAL_EMAIL="fweteam@aol.com"
ORG_SUPPORT_EMAIL="fweteam@aol.com"
ORG_TWITTER="0xfwe-team"
ORG_DESCRIPTION="fwe-team: Create Value to NFT Space"

[[PRINCIPALS]]
email="fweteam@aol.com"

[[CURRENCIES]]
code = "FWE"
name = "FWE"
issuer = "GCMHDOAGG65FSS657OLWFZWFDZUIDOKWCR2T73ZODPZYPPM3NK3YHOLY"
is_asset_anchored=false
display_decimals = 7
desc="This is token of FWE."
image="https://fwe-team.github.io/img/fwe.png"
conditions="There will only ever be 1 billion FWE tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
