# fweteam <fweteam.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GD7YDKEMKWHUIUJAQE5ZEEJ5US5KQQTT6X4QTHMFVX76WIRSUQOREWON"
]

[DOCUMENTATION]
ORG_NAME="fweteam"
ORG_URL="https://fweteam.github.io"
ORG_LOGO = "https://fweteam.github.io/img/fwe.png"
ORG_OFFICIAL_EMAIL="fwe.team@yahoo.com"
ORG_SUPPORT_EMAIL="fwe.team@yahoo.com"
ORG_TWITTER="0xfweteam"
ORG_DESCRIPTION="fweteam: Create Value to NFT Space"

[[PRINCIPALS]]
email="fwe.team@yahoo.com"

[[CURRENCIES]]
code = "FWE"
name = "FWE"
issuer = "GD7YDKEMKWHUIUJAQE5ZEEJ5US5KQQTT6X4QTHMFVX76WIRSUQOREWON"
is_asset_anchored=false
display_decimals = 7
desc="This is token of FWE."
image="https://fweteam.github.io/img/fwe.png"
conditions="There will only ever be 1 billion FWE tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
